### ISSUE TITLE
Tweet collector stuck in infinite loop

### ISSUE THREAD

**Issue by malidzanko** [Jefferson-Henrique/GetOldTweets-python#217] opened 2018-10-25 10:09 UTC
As of today when Tweet scraping is attempted, the module keeps returning same 20 tweets over and over again. Any idea why this is happening?

**Comment by Mottl** [comment] 2018-10-25 11:13
The issue is with incorrect get params handling during GET requests. Fixed version here:

**Comment by malidzanko** [comment] 2018-10-25 14:05
Thank you, your fix helped us locate what to change in our code.

**Comment by Mottl** [comment] 2018-10-25 14:08
Please reopen this issue, since it is not fixed at upstream (this repo).

**Comment by FelipeACJ** [comment] 2018-10-26 11:16
> Thank you, your fix helped us locate what to change in our code.

What line change in your code? please i need help. Regards

**Comment by Mottl** [comment] 2018-10-26 11:45
Check this commit:
https://github.com/Mottl/GetOldTweets3/commit/5049798f165bc195cce69cc9fb6ecf29a4eac192

**Comment by arijit1410** [comment] 2018-10-28 10:32
> The issue is caused by the incorrect GET parameters handling during HTTP requests. Fixed version is here: https://github.com/Mottl/GetOldTweets3
> or `pip install GetOldTweets3`

Thanks man you saved me so much time I can't even begin to describe how thankful I am.

**Comment by lanmnUC** [comment] 2018-11-09 17:43
To whoever is still using the ["Jefferson-Henrique/GetOldTweets-python",](https://github.com/Jefferson-Henrique/GetOldTweets-python) this issue can be fixed with one simple edition:
in "[GetOldTweets-python/got/manager/TweetManager.py](https://github.com/Jefferson-Henrique/GetOldTweets-python/blob/master/got/manager/TweetManager.py)",
at line [109](https://github.com/Jefferson-Henrique/GetOldTweets-python/blob/35482a21922abea624f2736f4566bf6a81480e62/got/manager/TweetManager.py#L109)
change
 `		url = url % (urllib.quote(urlGetData), refreshCursor)`
to
 `		url = url % (urllib.quote(urlGetData), urllib.quote(refreshCursor))`

This edition is inspired by https://github.com/Jefferson-Henrique/GetOldTweets-python/issues/217#issuecomment-433380953, Thanks for @Mottl !

**Comment by Jefferson-Henrique** [comment] 2018-11-21 11:41
Thanks @Mottl @lannUC  @malidzanko . I have used your contributions in my last commit to solve this loop thing.

**Closed by Jefferson-Henrique** 2018-11-21 11:41 UTC
